data: synthrad_3d
img_path:  ./data/synthrad_task2_brain/2BA001_ct.npz
cbct_path: ./data/synthrad_task2_brain/2BA001_cbct.npz

use_cbct_init: true
cbct_air_threshold: 0.08
cbct_ini_intensity: 0.20

img_size: [80, 256, 256]
num_proj: 20
proj_size: [512, 800]

air_threshold: 0.05
ini_intensity: 0.25
ini_sigma: 0.15
start: 0.15
spatial_lr_scale: 1

num_gaussian: 50000
max_gaussians: 300000
max_grad: 1.0e-05
min_intensity: 0.0001
sigma_extent: 2

do_density_control: true
densify_from_iter: 0
densify_until_iter: 15000
densification_interval: 100

low_reso_stage: 5000
max_iter: 15000
log_iter: 100
val_iter: 100
display_image_num: 8
tv_weight: 0.0
